name: Build Snap (Docker)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Snap using Docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Snap in Docker
        run: |
          docker run --rm -t \
            -v "$PWD:/workspace" \
            -w /workspace \
            snapcore/snapcraft:stable \
            snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: percona-distribution-mongodb-80.snap
          path: ./*.snap
