name: Build Snap Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Snap (host mode)
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Snapcraft
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd squashfs-tools
          sudo snap install snapcraft --classic

      - name: Build Snap using host mode
        run: |
          export CRAFT_PROVIDERS=host
          snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: percona-distribution-mongodb-80.snap
          path: ./*.snap
